# Generated by Django 4.1 on 2022-08-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="U_ID",
            field=models.CharField(default="---", max_length=100),
        ),
    ]
